name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - yus/deploy_doxygen_test

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
              sudo apt update
              sudo apt install doxygen
      
      - name: Generate Doc
        run: doxygen ${{github.workspace}}/Doxyfile

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4